#define za for
#define dokler while
#define znak char
#define celo int
#define plavajoce float
#define realno double
#define dolgo long
#define vrni return
#define ce if
#define sicer else
#define prazno void
#define zamenjaj switch
#define primer case
#define dodelispomin malloc
#define sprosti free
#define sizeof velikost
#define glavni main
#define natisnio printf
#define skenirajo scanf
#define dnatisnio fprintf
#define dskenirajo fscanf
#define DATOTEKA FILE
